# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
name: Ben Gdovicak 
description: Thoughts and Projects of a Cleveland Software Developer
url: http://www.gdovicak.com
domain: www.gdovicak.com

markdown: kramdown
plugins: [jekyll-paginate]

kramdown:
  input: GFM
  syntax_highlighter: rouge


